spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shorurl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.163.com
    username: shortURL_official@163.com
    password: XPTLZDPKAWWHTSLI
    default-encoding: UTF-8
server:
  port: 8181

